Add statistics
opensupports/opensupports pull request #904
Opened 2020-09-25 19:12 UTC by mredigonda

2020-10-07 14:34 UTC, mredigonda commented on client/src/app/admin/panel/dashboard/admin-panel-stats.js
> +                endDate: 202009132359
I need to provide better defaults.

2020-10-22 23:12 UTC, ivandiazwm commented on server/controllers/system/stats.php
> +    public function handler() {
@mredigonda please escape variables anyways before adding it them to the query

2020-10-22 23:15 UTC, ivandiazwm commented on server/controllers/system/stats.php
> +    public function handler() {
@mredigonda also, keep in mind you can use bindings with redbean
```
RedBean::getCell($query, $bindings);
```

2020-10-22 23:16 UTC, ivandiazwm requested changes
lgtm but use bindings before inserting variables in the sql query strings

2020-12-27 19:22 UTC, merged

2020-12-29 11:16 UTC, mredigonda commented
🥳 Tell me if something breaks. It would be amazing if we could test the SQL performance of this.